atTime(t0,isaItems(['towel_1','towel_2','towel_3'],tTowel)).
atTime(t0,isaItems(['wallet','sleeping_bag','shirts','shampoo','padlock','hair_trimmers','hair_brush','food_cans','can_opener','camouflage'],tStuff)).
atTime(t0,isaItems(['woodmans','walmart_oswego','tigerdirect','starbucks_aurora','frys','cvs_indian_trail_and_orchard','caribou_coffee_batavia'],tStore)).
atTime(t0,isaItems(['landing_to_second_floor_stairwell','first_floor_to_landing_stairwell','entry_to_first_floor_stairwell','basement_to_entry_stairwell'],tStairwell)).
atTime(t0,isaItems(['utility_room','garage','crawl_space','balcony'],tSpace)).
atTime(t0,isaItems(['upstairs_shower'],tShower)).
atTime(t0,isaItems(['clothing_grey_shirt_2 clothing_grey_shirt_1 clothing_green_shirt_1 clothing_blue_shirt_1'],tShirt)).
atTime(t0,isaItems(['living_room','kitchen','dining_room','bedroom'],tRoom)).
atTime(t0,isaItems(['andrew_dougherty'],tPerson)).
atTime(t0,isaItems(['front_door','balcony_door'],tPerimeterDoor)).
atTime(t0,isaItems(['clothing_khaki_shorts_2','clothing_khaki_shorts_1'],tPants)).
atTime(t0,isaItems(['upstairs_bathroom_outlets','kitchen_outlets','den_outlets'],tOutlet)).
atTime(t0,isaItems(['den'],tOfficeroom)).
atTime(t0,isaItems(['meal_velveeta_shells_and_cheese','meal_pindi_chana','meal_palek_paneer','meal_miso_soup'],tMealtype)).
atTime(t0,isaItems(['laptop_backpack'],tLockableContainer)).
atTime(t0,isaItems(['outside'],tLocation)).
atTime(t0,isaItems(['upstairs_washer'],tLaundryWashingMachine)).
atTime(t0,isaItems(['laundry_load'],tLaundryLoad)).
atTime(t0,isaItems(['upstairs_dryer'],tLaundryDryerMachine)).
atTime(t0,isaItems(['columcille_computer'],tLaptop)).
atTime(t0,isaItems(['second_floor_landing','landing'],tLanding)).
atTime(t0,isaItems(['finger_clippers'],tHygieneTool)).
atTime(t0,isaItems(['garage_entry_way','entry'],tEntryWay)).
atTime(t0,isaItems(['electric_razor_0'],tElectricRazor)).
atTime(t0,isaItems(['garage_door','den_door','crawl_space_door','basement_door'],tDoor)).
atTime(t0,isaItems(['computer_desk'],tDesk)).
atTime(t0,isaItems(['Wednesday','Tuesday','Thursday','Sunday','Saturday','Monday','Friday'],tDay)).
atTime(t0,isaItems(['date_20120827','date_20120826','date_20120825','date_20120824','date_20120823','date_20120822','date_20120821'],tDate)).
atTime(t0,isaItems(['dennis_computer'],tComputer)).
atTime(t0,isaItems(['landing_closet','kitchen_closet','dining_room_closet','coat_closet','bedroom_closet'],tCloset)).
atTime(t0,isaItems(['townhome'],tBuilding)).
atTime(t0,isaItems(['guestbed','couch'],tBed)).
atTime(t0,isaItems(['cell_phone','bluetooth_headset'],tBatteryPoweredDevice)).
atTime(t0,isaItems(['upstairs_bathroom','guest_bathroom'],tBathroom)).
atTime(t0,equals('charge_level'('bluetooth_headset'),'0.3')).
atTime(t0,equals('charge_level'('cell_phone'),'0.1')).
atTime(t0,equals('charge_level'('columcille_computer'),'1')).
atTime(t0,equals('charge_level'('electric_razor_0'),'0.0')).
atTime(t0,equals('charge_rate'('bluetooth_headset'),'0.5')).
atTime(t0,equals('charge_rate'('cell_phone'),'1')).
atTime(t0,equals('charge_rate'('columcille_computer'),'0.6')).
atTime(t0,equals('charge_rate'('electric_razor_0'),'0.5')).
atTime(t0,equals('discharge_rate'('bluetooth_headset'),'0.01')).
atTime(t0,equals('discharge_rate'('cell_phone'),'0.07')).
atTime(t0,equals('discharge_rate'('columcille_computer'),'0.3')).
atTime(t0,equals('discharge_rate'('electric_razor_0'),'2.5')).
atTime(t0,equals('fee_for_use'('upstairs_dryer'),'0')).
atTime(t0,equals('fee_for_use'('upstairs_washer'),'0')).
atTime(t0,equals('hours_worked_on_date'('andrew_dougherty','date_20120821'),'0')).
atTime(t0,equals('hours_worked_on_date'('andrew_dougherty','date_20120822'),'0')).
atTime(t0,equals('hours_worked_on_date'('andrew_dougherty','date_20120823'),'0')).
atTime(t0,equals('hours_worked_on_date'('andrew_dougherty','date_20120824'),'0')).
atTime(t0,equals('how_filling'('meal_miso_soup','andrew_dougherty'),'0.7')).
atTime(t0,equals('how_filling'('meal_palek_paneer','andrew_dougherty'),'0.4')).
atTime(t0,equals('how_filling'('meal_pindi_chana','andrew_dougherty'),'0.4')).
atTime(t0,equals('how_filling'('meal_velveeta_shells_and_cheese','andrew_dougherty'),'1.0')).
atTime(t0,equals('hunger_level'('andrew_dougherty'),'1').
atTime(t0,equals(quantity('meal_miso_soup','kitchen_closet'),'3')).
atTime(t0,equals(quantity('meal_palek_paneer','kitchen_closet'),'2')).
atTime(t0,equals(quantity('meal_pindi_chana','kitchen_closet'),'2')).
atTime(t0,equals(quantity('meal_velveeta_shells_and_cheese','kitchen_closet'),'1')).
atTime(t0,equals('rate_of_eating'('andrew_dougherty'),'5.0')).
atTime(t0,equals(speed('andrew_dougherty'),'1')).
atTime(t0,equals('total_walking_distance','0')).

at('0',inaccessible('walmart_oswego')).
at('0',isolated('living_room')).
at('23',isolated('living_room')).
at('31',not(isolated('living_room'))).
at('7',not(inaccessible('walmart_oswego'))).
at('7',not(isolated('living_room'))).

atTime(t0,'at_location'('andrew_dougherty',den)).
atTime(t0,'at_location'(balcony,townhome)).
atTime(t0,'at_location'('basement_to_entry_stairwell',townhome)).
atTime(t0,'at_location'(bedroom,townhome)).
atTime(t0,'at_location'('bedroom_closet',townhome)).
atTime(t0,'at_location'('clothing_blue_shirt_1',bedroom)).
atTime(t0,'at_location'('clothing_green_shirt_1',bedroom)).
atTime(t0,'at_location'('clothing_grey_shirt_1',bedroom)).
atTime(t0,'at_location'('clothing_grey_shirt_2',bedroom)).
atTime(t0,'at_location'('clothing_khaki_shorts_1',bedroom)).
atTime(t0,'at_location'('clothing_khaki_shorts_2',bedroom)).
atTime(t0,'at_location'('coat_closet',townhome)).
atTime(t0,'at_location'('columcille_computer','living_room')).
atTime(t0,'at_location'('computer_desk',den)).
atTime(t0,'at_location'(couch,'living_room')).
atTime(t0,'at_location'('crawl_space',townhome)).
atTime(t0,'at_location'(den,townhome)).
atTime(t0,'at_location'('den_outlets',den)).
atTime(t0,'at_location'('dennis_computer',den)).
atTime(t0,'at_location'('dining_room',townhome)).
atTime(t0,'at_location'('dining_room_closet',townhome)).
atTime(t0,'at_location'('electric_razor_0','upstairs_bathroom')).
atTime(t0,'at_location'(entry,townhome)).
atTime(t0,'at_location'('entry_to_first_floor_stairwell',townhome)).
atTime(t0,'at_location'('finger_clippers',den)).
atTime(t0,'at_location'('first_floor_to_landing_stairwell',townhome)).
atTime(t0,'at_location'(garage,townhome)).
atTime(t0,'at_location'('garage_entry_way',townhome)).
atTime(t0,'at_location'('guest_bathroom',townhome)).
atTime(t0,'at_location'(guestbed,bedroom)).
atTime(t0,'at_location'(kitchen,townhome)).
atTime(t0,'at_location'('kitchen_closet',townhome)).
atTime(t0,'at_location'('kitchen_outlets',kitchen)).
atTime(t0,'at_location'(landing,townhome)).
atTime(t0,'at_location'('landing_closet',townhome)).
atTime(t0,'at_location'('landing_to_second_floor_stairwell',townhome)).
atTime(t0,'at_location'('laptop_backpack',den)).
atTime(t0,'at_location'('laundry_load',bedroom)).
atTime(t0,'at_location'('living_room',townhome)).
atTime(t0,'at_location'('second_floor_landing',townhome)).
atTime(t0,'at_location'('towel_1',bedroom)).
atTime(t0,'at_location'('towel_2',bedroom)).
atTime(t0,'at_location'('towel_3',bedroom)).
atTime(t0,'at_location'('upstairs_bathroom',townhome)).
atTime(t0,'at_location'('upstairs_bathroom_outlets','upstairs_bathroom')).
atTime(t0,'at_location'('upstairs_dryer','utility_room')).
atTime(t0,'at_location'('upstairs_shower','upstairs_bathroom')).
atTime(t0,'at_location'('upstairs_washer','utility_room')).
atTime(t0,'at_location'('utility_room',townhome)).
atTime(t0,autonomous('andrew_dougherty')).
atTime(t0,dirty('clothing_blue_shirt_1')).
atTime(t0,dirty('clothing_green_shirt_1')).
atTime(t0,dirty('clothing_grey_shirt_1')).
atTime(t0,dirty('clothing_grey_shirt_2')).
atTime(t0,dirty('clothing_khaki_shorts_1')).
atTime(t0,dirty('clothing_khaki_shorts_2')).
atTime(t0,dirty(den)).
atTime(t0,dirty(garage)).
atTime(t0,dirty('towel_1')).
atTime(t0,dirty('towel_2')).
atTime(t0,dirty('towel_3')).
atTime(t0,dirty('upstairs_bathroom')).
atTime(t0,exhausted('andrew_dougherty')).
atTime(t0,'has_door'('balcony_door',balcony,'dining_room')).
atTime(t0,'has_door'('basement_door',garage,'garage_entry_way')).
atTime(t0,'has_door'('crawl_space_door','crawl_space','garage_entry_way')).
atTime(t0,'has_door'('den_door',den,'garage_entry_way')).
atTime(t0,'has_door'('front_door',entry,outside)).
atTime(t0,'has_door'('garage_door',garage,outside)).
atTime(t0,'has_permission_to_use'('andrew_dougherty','upstairs_bathroom')).
atTime(t0,'locked_door'('basement_door')).
atTime(t0,'locked_door'('front_door')).
atTime(t0,'locked_door'('garage_door')).
atTime(t0,mobile('bluetooth_headset')).
atTime(t0,mobile('cell_phone')).
atTime(t0,mobile('clothing_blue_shirt_1')).
atTime(t0,mobile('clothing_green_shirt_1')).
atTime(t0,mobile('clothing_grey_shirt_1')).
atTime(t0,mobile('clothing_grey_shirt_2')).
atTime(t0,mobile('clothing_khaki_shorts_1')).
atTime(t0,mobile('clothing_khaki_shorts_2')).
atTime(t0,mobile('columcille_computer')).
atTime(t0,mobile('electric_razor_0')).
atTime(t0,mobile('finger_clippers')).
atTime(t0,mobile('laptop_backpack')).
atTime(t0,mobile('laundry_load')).
atTime(t0,mobile('towel_1')).
atTime(t0,mobile('towel_2')).
atTime(t0,mobile('towel_3')).
atTime(t0,'plugged_in'('dennis_computer')).
atTime(t0,wearing('andrew_dougherty','clothing_grey_shirt_1')).
